spring.application.name=ejemplodemo
server.port=8080

# ==============================================================================
# Configuración para conectar MySQL/MariaDB de XAMPP
# ==============================================================================
spring.datasource.url=jdbc:mysql://localhost:3306/biblioteca_virtual?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA e Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Forzar el dialecto para evitar el error de metadata en XAMPP
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect